FROM opensearchproject/opensearch:2.12.0

# Install the opensearch-ubi plugin.
RUN /usr/share/opensearch/bin/opensearch-plugin install https://github.com/o19s/opensearch-ubi/releases/download/0.0.7/opensearch-ubi.zip
